#!/usr/bin/env python
# -*- coding: utf-8 -*-
import xml.etree.cElementTree as ET
import pprint
import re

def key_type(element, keys):
    if element.tag == "way" or element.tag == "node":
        tags = element.findall("tag")
        for tag in tags:
            if tag.tag == "tag":
                key = tag.attrib['k']
                keySplit = re.split('\:', key)
                keys = check_key(keys, keySplit)
    return keys

def process_map(filename):
    #keys = recursive_defaultdict()
    keys = {}
    for _, element in ET.iterparse(filename):
        keys = key_type(element, keys)
    return keys

def check_key(keyDict, keyList):
    if len(keyList) == 1:

        if keyList[0] in keyDict:
            if "Total" in keyDict[keyList[0]]:
                keyDict[keyList[0]]["Total"] += 1
            else:
                keyDict[keyList[0]]["Total"] = 1
        else:
            keyDict[keyList[0]] = {"Total": 1}
    else:
        if keyList[0] not in keyDict:
            keyDict[keyList[0]] = {}
        check_key(keyDict[keyList[0]], keyList[1:])
    return keyDict

def run():
    keys = process_map('barcelona_spain.osm')
    #pprint.pprint(keys)
    pprint.pprint({ k:v for k, v in keys.items() if (v > 100) })

if __name__ == "__main__":
    run()


'''
{'BORDER_COL': {'Total': 3},
 'BORDER_STY': {'Total': 3},
 'BORDER_WID': {'Total': 3},
 'CIF': {'Total': 2},
 'CLOSED': {'Total': 3},
 'FILL_STYLE': {'Total': 3},
 'FIXME': {'Total': 12},
 'Fresser': {'Total': 1},
 'GM_TYPE': {'Total': 3},
 'Generalitat': {'Total': 1},
 'LAYER': {'Total': 3},
 u'L\xedneas': {'Total': 2},
 'Motor home': {'Total': 1},
 'Passeig Dos de Maig': {'Total': 2},
 'Restes': {'Total': 6},
 '_description_': {'Total': 341},
 '_ref': {'Total': 1},
 'abandoned': {'Total': 8, 'gas': {'Total': 1}, 'highway': {'Total': 1}},
 'abutters': {'Total': 4},
 'access': {'Total': 3231,
            'conditional': {'Total': 4},
            'lanes': {'backward': {'Total': 7}, 'forward': {'Total': 12}}},
 'addr': {'city': {'Total': 11559},
          'country': {'Total': 774},
          'district': {'Total': 32},
          'door': {'Total': 1},
          'floor': {'Total': 8},
          'full': {'Total': 3},
          'housename': {'Total': 235},
          'housenumber': {'Total': 12210},
          'inclusion': {'Total': 6},
          'interpolation': {'Total': 13},
          'place': {'Total': 5},
          'postcode': {'Total': 6440},
          'province': {'Total': 2},
          'state': {'Total': 62},
          'street': {'Total': 13779},
          'unit': {'Total': 16}},
 'addr1': {'housenumber': {'Total': 1}, 'street': {'Total': 1}},
 'address': {'Total': 1},
 'admin_level': {'Total': 312},
 'aerialway': {'Total': 13},
 'aerodrome': {'Total': 1},
 'aeroway': {'Total': 647},
 'agricultural': {'Total': 7},
 'alcohol': {'Total': 1},
 'alt': {'Total': 1, 'name': {'Total': 6}},
 'alt_name': {'Total': 418, 'ca': {'Total': 1}, 'ru': {'Total': 1}},
 'alt_name2': {'Total': 1},
 'altitude': {'Total': 1},
 'amenity': {'Total': 10861, 'ca': {'Total': 1}, 'es': {'Total': 1}},
 'amenity_1': {'Total': 1},
 'amenity_2': {'Total': 1},
 'animal': {'Total': 2},
 'animal_shelter': {'Total': 1, 'adoption': {'Total': 1}},
 'architect': {'Total': 55},
 'area': {'Total': 1220, 'highway': {'Total': 106}},
 'artist': {'Total': 1},
 'artist_name': {'Total': 33},
 'artwork': {'Total': 1},
 'artwork_type': {'Total': 70},
 'association': {'Total': 12},
 'atm': {'Total': 360, 'network': {'Total': 186}, 'operator': {'Total': 60}},
 'attraction': {'Total': 21},
 'authentication': {'none': {'Total': 2}},
 'author': {'Total': 1},
 'automated': {'Total': 7},
 'award': {'michelin': {'Total': 1}},
 'backrest': {'Total': 373},
 'bakery': {'Total': 2},
 'bank': {'network': {'Total': 3}},
 'bar': {'Total': 1},
 'barrier': {'Total': 4406},
 'beacon': {'Total': 2},
 'bench': {'Total': 385},
 'bic': {'Total': 1},
 'bicycle': {'Total': 3634},
 'bicycle_parking': {'Total': 36},
 'bicycle_road': {'Total': 1},
 'biergarten': {'Total': 1},
 'bin': {'Total': 2},
 'board_type': {'Total': 21},
 'boat': {'Total': 35},
 'bollard': {'Total': 26},
 'bolted': {'Total': 1},
 'boules': {'Total': 6},
 'boundary': {'Total': 263},
 'brand': {'Total': 50},
 'bridge': {'Total': 1797, 'movable': {'Total': 1}},
 'building': {'Total': 30984,
              'century': {'Total': 1},
              'colour': {'Total': 217},
              'condition': {'Total': 1},
              'facade': {'colour': {'Total': 10}, 'material': {'Total': 111}},
              'height': {'Total': 172},
              'levels': {'Total': 3533, 'underground': {'Total': 3}},
              'material': {'Total': 185},
              'min_height': {'Total': 7},
              'min_level': {'Total': 425},
              'part': {'Total': 2090},
              'roof': {'material': {'Total': 4}},
              'shape': {'Total': 38},
              'use': {'Total': 23},
              'year': {'Total': 34}},
 'bus': {'Total': 554, 'backward': {'Total': 1}},
 'busway': {'Total': 4, 'right': {'Total': 5}},
 'butcher': {'Total': 4},
 'button_operated': {'Total': 1},
 'cables': {'Total': 27},
 'capacity': {'Total': 223,
              'disabled': {'Total': 30},
              'parent': {'Total': 23},
              'women': {'Total': 22}},
 'capital': {'Total': 86},
 'car': {'Total': 2},
 'castle_type': {'Total': 1},
 'catastro': {'ref': {'Total': 9}},
 'chain': {'Total': 1},
 'change': {'lanes': {'backward': {'Total': 16}, 'forward': {'Total': 26}}},
 'check_date': {'Total': 2},
 'cif': {'Total': 14},
 'cinema': {'3D': {'Total': 3}},
 'circuits': {'Total': 1},
 'climbing': {'Total': 6},
 'clothes': {'Total': 8},
 'club': {'Total': 5},
 'cmt': {'Total': 3},
 'coffee': {'Total': 3},
 'collection_times': {'Total': 10},
 'colour': {'Total': 275},
 'comment': {'Total': 3},
 'company': {'Total': 1},
 'construction': {'Total': 86, 'railway': {'Total': 7}},
 'contact': {'email': {'Total': 112},
             'facebook': {'Total': 2},
             'fax': {'Total': 40},
             'phone': {'2': {'Total': 1}, 'Total': 175},
             'twitter': {'Total': 1},
             'website': {'Total': 132}},
 'content': {'Total': 1},
 'context': {'Total': 1},
 'converted_by': {'Total': 53},
 'conveying': {'Total': 8},
 'country': {'Total': 7},
 'covered': {'Total': 264},
 'craft': {'Total': 36},
 'craft_1': {'Total': 1},
 'crane': {'type': {'Total': 2}},
 'created_by': {'Total': 1454},
 'crop': {'Total': 1},
 'crossing': {'Total': 3060,
              'barrier': {'Total': 170},
              'light': {'Total': 170}},
 'crossing_ref': {'Total': 156},
 'crown_type': {'Total': 11},
 'cuisine': {'Total': 621},
 'currency': {'EUR': {'Total': 8}},
 'cutting': {'Total': 38},
 'cycleway': {'Total': 1006, 'left': {'Total': 43}, 'right': {'Total': 9}},
 'dance': {'teaching': {'Total': 1}},
 'date': {'Total': 7},
 'defibrillator': {'location': {'Total': 1}},
 'delivery': {'Total': 10},
 'demolished': {'Total': 1},
 'denomination': {'Total': 117},
 'denotation': {'Total': 144},
 'density': {'Total': 1},
 'depot': {'vehicle': {'tram': {'Total': 1}}},
 'description': {'Total': 146,
                 'ca': {'Total': 1},
                 'en': {'Total': 3},
                 'es': {'Total': 1}},
 'designation': {'Total': 217},
 'desnivell': {'Total': 6},
 'destination': {'Total': 5, 'lanes': {'Total': 1}},
 'diaper': {'Total': 4},
 'diesel': {'Total': 1},
 'diet': {'Total': 3,
          'gluten_free': {'Total': 2},
          'raw': {'Total': 1},
          'vegan': {'Total': 4},
          'vegetarian': {'Total': 15}},
 'diplomatic': {'Total': 4},
 'direction': {'Total': 30},
 'dispensing': {'Total': 125},
 'display': {'Total': 7},
 'disused': {'Total': 11, 'route': {'Total': 2}},
 'dock': {'Total': 1},
 'dog': {'Total': 6},
 'doityourself': {'Total': 1},
 'dolmen': {'Total': 1},
 'drink': {'beer': {'Total': 2}, 'club-mate': {'Total': 14}},
 'drinkable': {'Total': 3},
 'drinking_water': {'Total': 6, 'legal': {'Total': 1}},
 'drive_in': {'Total': 1},
 'drive_through': {'Total': 2},
 'duration': {'Total': 10},
 'ele': {'Total': 184, 'msl': {'Total': 1}, 'source': {'Total': 1}},
 'electrified': {'Total': 1101},
 'elevator': {'Total': 2},
 'email': {'Total': 163},
 'embankment': {'Total': 16},
 'emergency': {'Total': 1012},
 'end_date': {'Total': 7},
 'enterprice': {'Total': 1},
 'entrance': {'Total': 2487},
 'escalator': {'Total': 14},
 'escalator_dir': {'Total': 1},
 'est_height': {'Total': 1},
 'est_width': {'Total': 34},
 'exit_to': {'Total': 206},
 'facebook': {'Total': 2},
 'faces': {'Total': 1},
 'factory': {'Total': 1},
 'farm': {'Total': 1},
 'farmhouse': {'Total': 2},
 'fax': {'Total': 80},
 'feature': {'Total': 1},
 'fee': {'Total': 359,
         'day': {'Total': 1},
         'hour': {'Total': 1},
         'minute': {'Total': 1}},
 'fee_amount': {'Total': 1},
 'female': {'Total': 2},
 'fence': {'Total': 2},
 'fence_type': {'Total': 62},
 'fenced': {'Total': 10},
 'ferry': {'Total': 2},
 'fire_hydrant': {'count': {'Total': 11},
                  'coupling_type': {'Total': 208},
                  'couplings': {'Total': 102},
                  'diameter': {'Total': 161},
                  'flow_capacity': {'Total': 18},
                  'position': {'Total': 239},
                  'pressure': {'Total': 70},
                  'type': {'Total': 803}},
 'fireplace': {'Total': 1},
 'fixme': {'Total': 93},
 'food': {'Total': 14},
 'foot': {'Total': 3785},
 'footway': {'Total': 929},
 'ford': {'Total': 6},
 'founded': {'Total': 1},
 'frequency': {'Total': 1071},
 'frozen': {'Total': 1},
 'fuel': {'1_25': {'Total': 3},
          '1_50': {'Total': 3},
          'GTL_diesel': {'Total': 137},
          'HGV_diesel': {'Total': 7},
          'Total': 15,
          'biodiesel': {'Total': 33},
          'biogas': {'Total': 3},
          'cng': {'Total': 3},
          'diesel': {'Total': 186},
          'diesel_B': {'Total': 8},
          'diesel_C': {'Total': 5},
          'e10': {'Total': 3},
          'e85': {'Total': 3},
          'electricity': {'Total': 3},
          'lpg': {'Total': 4},
          'octane_100': {'Total': 3},
          'octane_91': {'Total': 4},
          'octane_95': {'Total': 185},
          'octane_98': {'Total': 171}},
 'fully_enclosed': {'Total': 1},
 'funicular': {'Total': 1},
 'gambling': {'Total': 2},
 'games': {'Total': 7},
 'gate': {'Total': 1},
 'gauge': {'Total': 1201},
 'gay': {'Total': 8, 'men': {'Total': 2}, 'woman': {'Total': 1}},
 'generator': {'method': {'Total': 5}, 'source': {'Total': 8}},
 'genus': {'Total': 16},
 'gml_featuretype': {'Total': 3},
 'goods': {'Total': 23},
 'google_plus': {'Total': 1},
 'grade': {'french': {'max': {'Total': 1}, 'min': {'Total': 1}}},
 'handicapped': {'Total': 1},
 'handrail': {'Total': 16,
              'center': {'Total': 1},
              'left': {'Total': 3},
              'right': {'Total': 4}},
 'hazmat': {'Total': 35},
 'health_facility': {'type': {'Total': 7}},
 'health_person': {'type': {'Total': 1}},
 'health_specialty': {'physiotherapy': {'Total': 5}},
 'healthcare': {'Total': 3, 'speciality': {'Total': 1}},
 'height': {'Total': 983, 'source': {'Total': 2}},
 'heritage': {'Total': 12, 'operator': {'Total': 10}},
 'hgv': {'Total': 45},
 'highspeed': {'Total': 107},
 'highway': {'Total': 59701},
 'hiking': {'Total': 48},
 'historic': {'Total': 280,
              'century': {'Total': 17},
              'civilization': {'Total': 1},
              'status': {'Total': 1}},
 'historical': {'Total': 1},
 'history': {'Total': 26},
 'hoops': {'Total': 11},
 'horaris': {'Total': 1},
 'horse': {'Total': 1515},
 'hov': {'Total': 19},
 'iata': {'Total': 1},
 'icao': {'Total': 2},
 'idee': {'name': {'Total': 2}},
 'ideewfs': {'alturaElipsoidal': {'Total': 3},
             'convergencia': {'Total': 3},
             'factorEscala': {'Total': 3},
             'husoUTM': {'Total': 3},
             'latitud': {'Total': 3},
             'longitud': {'Total': 3},
             'nombre': {'Total': 3},
             'numeroROI': {'Total': 3},
             'xUTM': {'Total': 3},
             'yUTM': {'Total': 3}},
 'ign': {'latitud': {'Total': 20},
         'longitud': {'Total': 20},
         'red': {'Total': 20}},
 'illegal': {'amenity': {'Total': 2}, 'building': {'Total': 2}},
 'image': {'Total': 4},
 'importance': {'Total': 1},
 'in_service': {'Total': 2},
 'incline': {'Total': 139},
 'indoor': {'Total': 98},
 'industrial': {'Total': 4},
 'ine': {'municipio': {'Total': 2}},
 'information': {'Total': 140},
 'inscription': {'Total': 2, 'en': {'Total': 1}},
 'int_name': {'Total': 31},
 'int_ref': {'Total': 173},
 'intermittent': {'Total': 141},
 'internet_access': {'Total': 102,
                     'access': {'Total': 7},
                     'fee': {'Total': 48},
                     'ssid': {'Total': 5},
                     'wlan': {'bssid': {'Total': 2},
                              'channel': {'Total': 1},
                              'enc': {'Total': 2},
                              'essid': {'Total': 5},
                              'key': {'Total': 5}}},
 'is_in': {'Total': 156,
           'city': {'Total': 14},
           'continent': {'Total': 69},
           'country': {'Total': 341},
           'country_code': {'Total': 54},
           'county': {'Total': 1},
           'iso_3166_2': {'Total': 1},
           'municipality': {'Total': 256},
           'province': {'Total': 230},
           'province_code': {'Total': 51},
           'region': {'Total': 64},
           'state': {'Total': 328},
           'state_code': {'Total': 327}},
 'isced': {'Total': 2, 'level': {'Total': 13}},
 'junction': {'Total': 1179},
 'kerb': {'Total': 58},
 'lamp_type': {'Total': 6},
 'lan': {'Total': 1},
 'landcover': {'Total': 117},
 'landscape': {'Total': 2},
 'landuse': {'Total': 5358},
 'lane': {'Total': 2},
 'lanes': {'Total': 4737,
           'backward': {'Total': 25},
           'bus': {'backward': {'Total': 1}},
           'forward': {'Total': 32},
           'psv': {'Total': 13, 'backward': {'Total': 1}},
           'reversible': {'Total': 1}},
 'latitude': {'Total': 1},
 'layer': {'Total': 3408},
 'leaf_cycle': {'Total': 48},
 'leaf_type': {'Total': 255},
 'leisure': {'Total': 6383},
 'length': {'Total': 4},
 'level': {'Total': 86},
 'levels': {'Total': 10},
 'linen': {'Total': 1},
 'lit': {'Total': 3096},
 'loc_name': {'Total': 20},
 'local_name': {'Total': 1},
 'local_ref': {'Total': 268},
 'location': {'Total': 45},
 'longitude': {'Total': 1},
 'main': {'Total': 1},
 'male': {'Total': 4},
 'man_made': {'Total': 529},
 'map_type': {'Total': 5},
 'material': {'Total': 374},
 'max_level': {'Total': 1},
 'maxheight': {'Total': 80},
 'maxlength': {'Total': 15},
 'maxspeed': {'Total': 5631, 'forward': {'Total': 2}},
 'maxstay': {'Total': 2},
 'maxweight': {'Total': 117},
 'maxwidth': {'Total': 1},
 'medical_system': {'western': {'Total': 5}},
 'megalith_type': {'Total': 1},
 'memorial': {'Total': 1},
 'menu_del_dia': {'Total': 3},
 'microbrewery': {'Total': 4},
 'military': {'Total': 18},
 'min_age': {'Total': 1},
 'min_height': {'Total': 117},
 'min_level': {'Total': 1},
 'minspeed': {'Total': 1},
 'monitoring': {'bicycle': {'Total': 1}},
 'monorail': {'Total': 1},
 'moped': {'Total': 3},
 'motor_vehicle': {'Total': 1060, 'backward': {'Total': 1}},
 'motorboat': {'Total': 1},
 'motorcar': {'Total': 110},
 'motorcycle': {'Total': 106},
 'motorroad': {'Total': 357},
 'mountain_pass': {'Total': 3},
 'mtb': {'Total': 21,
         'scale': {'Total': 245,
                   'imba': {'Total': 6},
                   'uphill': {'Total': 22}}},
 'multipitch': {'Total': 1},
 'name': {'Total': 39885,
          'alt': {'Total': 1},
          'an': {'Total': 3},
          'ar': {'Total': 2},
          'botanical': {'Total': 40},
          'ca': {'Total': 470},
          'cn': {'Total': 1},
          'de': {'Total': 15},
          'el': {'Total': 2},
          'en': {'Total': 61},
          'es': {'Total': 477},
          'eu': {'Total': 1},
          'fr': {'Total': 11},
          'he': {'Total': 20},
          'hi': {'Total': 1},
          'hu': {'Total': 1},
          'it': {'Total': 1},
          'ja': {'Total': 3},
          'kn': {'Total': 1},
          'pl': {'Total': 1},
          'ru': {'Total': 62},
          'sr': {'Total': 3},
          'uk': {'Total': 10},
          'zh': {'Total': 2}},
 'name_1': {'Total': 4},
 'name_alt': {'Total': 2},
 'name_old': {'es': {'Total': 1}},
 'nat_ref': {'Total': 3},
 'natural': {'Total': 6513},
 'nature': {'Total': 11},
 'navigation_aid': {'Total': 1},
 'navigationaid': {'Total': 1},
 'network': {'Total': 855},
 'noexit': {'Total': 96},
 'note': {'Total': 730, 'ca': {'Total': 1}, 'es': {'Total': 4}},
 'nudism': {'Total': 1},
 'obstacle': {'Total': 32,
              'motorcar': {'Total': 2},
              'wheelchair': {'Total': 2}},
 'office': {'Total': 217},
 'official_name': {'Total': 24, 'hu': {'Total': 1}},
 'old': {'Total': 1},
 'old_name': {'Total': 79,
              'ca': {'Total': 1},
              'en': {'Total': 1},
              'es': {'Total': 1}},
 'old_ref': {'Total': 25},
 'on': {'Total': 1},
 'oneway': {'Total': 22773, 'bicycle': {'Total': 31}, 'psv': {'Total': 1}},
 'opening_date': {'Total': 53},
 'opening_hours': {'Total': 568, 'url': {'Total': 3}},
 'opensource': {'Total': 1},
 'operator': {'Total': 2263},
 'operator_1': {'Total': 1},
 'organic': {'Total': 7},
 'outdoor_seating': {'Total': 48},
 'overtaking': {'Total': 5},
 'owner': {'Total': 1},
 'park_ride': {'Total': 58},
 'parking': {'Total': 540,
             'condition': {'Total': 1,
                           'both': {'Total': 68, 'vehicles': {'Total': 1}},
                           'left': {'Total': 54, 'vehicles': {'Total': 2}},
                           'right': {'Total': 66, 'vehicles': {'Total': 5}}},
             'lane': {'Total': 21,
                      'both': {'Total': 124,
                               'diagonal': {'Total': 1},
                               'parallel': {'Total': 29}},
                      'left': {'Total': 76,
                               'capacity': {'Total': 2},
                               'diagonal': {'Total': 6},
                               'parallel': {'Total': 34},
                               'perpendicular': {'Total': 2}},
                      'parallel': {'Total': 2},
                      'right': {'Total': 85,
                                'capacity': {'Total': 1},
                                'diagonal': {'Total': 5},
                                'parallel': {'Total': 40},
                                'perpendicular': {'Total': 4}}},
             'lanes': {'both': {'Total': 2}}},
 'parts': {'Total': 1},
 'passenger_information_display': {'Total': 138},
 'passing_places': {'Total': 1},
 'pastry_shop': {'Total': 1},
 'payment': {'account_cards': {'Total': 3},
             'bitcoin': {'Total': 22},
             'coins': {'Total': 38},
             'credit_cards': {'Total': 2},
             'debit_cards': {'Total': 2},
             'electronic_purses': {'Total': 4},
             'litecoin': {'Total': 2},
             'notes': {'Total': 1},
             'telephone_cards': {'Total': 19},
             'vertcoin': {'Total': 1}},
 'pet': {'Total': 1},
 'phone': {'Total': 911},
 'piste': {'difficulty': {'Total': 3},
           'grooming': {'Total': 3},
           'type': {'Total': 1}},
 'pk': {'Total': 7},
 'place': {'Total': 651},
 'plant': {'output': {'electricity': {'Total': 2}}},
 'platforms': {'Total': 18},
 'playground': {'Total': 2},
 'population': {'Total': 102, 'date': {'Total': 38}},
 'postal_code': {'Total': 9},
 'power': {'Total': 2007},
 'power_source': {'Total': 1},
 'private': {'Total': 3},
 'product': {'Total': 3},
 'proposed': {'Total': 11},
 'psv': {'Total': 72, 'backward': {'Total': 1}},
 'public_transport': {'Total': 1143},
 'railway': {'Total': 3158,
             'etcs': {'Total': 94},
             'milestone': {'catenary_mast': {'Total': 2}},
             'position': {'Total': 1, 'exact': {'Total': 2}},
             'switch': {'Total': 1},
             'track_ref': {'Total': 2},
             'traffic_mode': {'Total': 94},
             'turnout_side': {'Total': 1}},
 'ramp': {'Total': 25, 'luggage': {'Total': 2}, 'wheelchair': {'Total': 1}},
 'rank': {'Total': 1},
 'rapid_exit': {'Total': 1},
 'reconstruction': {'Total': 9},
 'recycling': {'aluminium': {'Total': 1},
               'batteries': {'Total': 45},
               'books': {'Total': 35},
               'cans': {'Total': 289},
               'car_batteries': {'Total': 1},
               'cardboard': {'Total': 60},
               'cartons': {'Total': 37},
               'clothes': {'Total': 167},
               'computers': {'Total': 1},
               'cooking_oil': {'Total': 1},
               'electrical_appliances': {'Total': 36},
               'electrical_items': {'Total': 1},
               'engine_oil': {'Total': 1},
               'fluorescent_tubes': {'Total': 1},
               'furniture': {'Total': 1},
               'garden_waste': {'Total': 1},
               'glass': {'Total': 311},
               'glass_bottles': {'Total': 36},
               'green_waste': {'Total': 118},
               'hazardous_waste': {'Total': 1},
               'low_energy_bulbs': {'Total': 1},
               'magazines': {'Total': 33},
               'metal': {'Total': 1},
               'mobile_phones': {'Total': 1},
               'newspaper': {'Total': 35},
               'organic': {'Total': 8},
               'packaging': {'Total': 2},
               'paper': {'Total': 310},
               'paper_packaging': {'Total': 35},
               'plastic': {'Total': 156},
               'plastic_bottles': {'Total': 36},
               'plastic_packaging': {'Total': 34},
               'scrap_metal': {'Total': 45},
               'small_appliances': {'Total': 34},
               'styrofoam': {'Total': 1},
               'tv_monitor': {'Total': 1},
               'tyres': {'Total': 1},
               'waste': {'Total': 46},
               'white_goods': {'Total': 1},
               'wood': {'Total': 35}},
 'recycling_type': {'Total': 260},
 'rednap': {'altitudortometrica': {'Total': 40},
            'codigoine': {'Total': 40},
            'ficha': {'Total': 40},
            'grupo': {'Total': 40},
            'latitud': {'Total': 40},
            'longitud': {'Total': 40},
            'nodo': {'Total': 40},
            'numero': {'Total': 40},
            'posicion': {'Total': 40},
            'tipo': {'Total': 40}},
 'ref': {'AEFE': {'Total': 1},
         'BCIN': {'Total': 1},
         'RRG': {'Total': 3},
         'Total': 4444,
         'alt': {'Total': 14},
         'colour': {'Total': 2},
         'idescat': {'Total': 1},
         'ine': {'Total': 49}},
 'reg_name': {'Total': 2},
 'reg_ref': {'Total': 2},
 'religion': {'Total': 226},
 'repair': {'Total': 2},
 'resource': {'Total': 6},
 'restriction': {'Total': 14},
 'rock': {'Total': 1},
 'roller_coaster': {'Total': 6},
 'roof': {'angle': {'Total': 1},
          'colour': {'Total': 279},
          'height': {'Total': 148},
          'levels': {'Total': 121},
          'material': {'Total': 374},
          'orientation': {'Total': 73},
          'shape': {'Total': 437},
          'slope': {'direction': {'Total': 28}},
          'type': {'Total': 4}},
 'room': {'Total': 5},
 'rooms': {'Total': 7},
 'route': {'Total': 110},
 'route_ref': {'Total': 89},
 'route_ref_1': {'Total': 1},
 'ruin': {'Total': 1},
 'ruins': {'Total': 23},
 'runway_ref': {'Total': 1},
 'sac_scale': {'Total': 232},
 'sac_scale_ref': {'Total': 2},
 'safety_rope': {'Total': 2},
 'sale': {'Total': 1},
 'school': {'Total': 4},
 'scooter': {'Total': 2},
 'seamark': {'beacon_cardinal': {'category': {'Total': 5},
                                 'colour': {'Total': 5},
                                 'colour_pattern': {'Total': 5},
                                 'height': {'Total': 3},
                                 'shape': {'Total': 1}},
             'buoy_safe_water': {'colour': {'Total': 1},
                                 'colour_pattern': {'Total': 1},
                                 'shape': {'Total': 1}},
             'harbour': {'category': {'Total': 1}},
             'information': {'Total': 4},
             'light': {'1': {'character': {'Total': 2},
                             'colour': {'Total': 2},
                             'group': {'Total': 1},
                             'height': {'Total': 2},
                             'period': {'Total': 1},
                             'range': {'Total': 2},
                             'sector_end': {'Total': 2},
                             'sector_start': {'Total': 2},
                             'sequence': {'Total': 2}},
                       'category': {'Total': 1},
                       'character': {'Total': 25},
                       'colour': {'Total': 25},
                       'group': {'Total': 22},
                       'height': {'Total': 24},
                       'period': {'Total': 25},
                       'range': {'Total': 24},
                       'reference': {'Total': 25},
                       'sequence': {'Total': 15}},
             'light_major': {'height': {'Total': 2}},
             'light_minor': {'height': {'Total': 13}},
             'name': {'Total': 8},
             'radar_reflector': {'Total': 2},
             'radar_transponder': {'category': {'Total': 1},
                                   'group': {'Total': 1}},
             'type': {'Total': 28}},
 'seasonal': {'Total': 1},
 'seats': {'Total': 317},
 'second_hand': {'Total': 4},
 'segregated': {'Total': 140},
 'self_service': {'Total': 5},
 'sensory': {'Total': 1},
 'service': {'Total': 2575,
             'bicycle': {'rental': {'Total': 2},
                         'repair': {'Total': 1},
                         'retail': {'Total': 3}},
             'copy': {'Total': 1},
             'fax': {'Total': 1},
             'print': {'Total': 1}},
 'shade': {'Total': 2},
 'shelter': {'Total': 493},
 'shelter_type': {'Total': 10},
 'shooting': {'Total': 1},
 'shop': {'Total': 2220, 'ca': {'Total': 2}, 'es': {'Total': 2}},
 'shop_1': {'Total': 1},
 'short_name': {'Total': 10, 'ca': {'Total': 1}},
 'side': {'Total': 20},
 'sidewalk': {'Total': 358},
 'site': {'Total': 2},
 'site_type': {'Total': 1},
 'ski': {'Total': 30},
 'sloped_curb': {'Total': 79},
 'smoking': {'Total': 157},
 'smoothness': {'Total': 15},
 'snowmobile': {'Total': 30},
 'social_facility': {'Total': 12, 'for': {'Total': 11}},
 'social_facility_for': {'Total': 3},
 'socket': {'chademo': {'Total': 1}, 'schuko': {'Total': 3}},
 'sorting_name': {'Total': 2},
 'source': {'Total': 13834,
            'da': {'Total': 1},
            'date': {'Total': 2479},
            'ele': {'Total': 48},
            'file': {'Total': 49},
            'filename': {'Total': 3},
            'height': {'Total': 38},
            'name': {'Total': 93},
            'pop': {'Total': 11},
            'population': {'Total': 2},
            'ref': {'Total': 26},
            'url': {'Total': 1},
            'wfs': {'Total': 40}},
 'source_ref': {'Total': 3},
 'species': {'Total': 63, 'ca': {'Total': 11}, 'es': {'Total': 44}},
 'speed': {'Total': 1},
 'sport': {'Total': 1430},
 'square': {'Total': 1},
 'stairs': {'Total': 1},
 'stamps': {'Total': 1},
 'stars': {'Total': 76},
 'start_date': {'Total': 58},
 'station': {'Total': 294},
 'status': {'Total': 3},
 'step_count': {'Total': 38},
 'structure': {'Total': 6},
 'subject': {'Total': 1, 'wikidata': {'Total': 3}},
 'subway': {'Total': 375},
 'supervised': {'Total': 276},
 'support': {'Total': 5},
 'surface': {'Total': 5600},
 'surface_1': {'Total': 1},
 'surveillance': {'Total': 6, 'type': {'Total': 2}, 'zone': {'Total': 2}},
 'survey': {'date': {'Total': 2}},
 'switch': {'Total': 3},
 'sym': {'Total': 3},
 'tables': {'Total': 1},
 'tactile_paving': {'Total': 21},
 'takeaway': {'Total': 37},
 'tasting': {'Total': 1},
 'taxi': {'Total': 15},
 'team': {'Total': 1},
 'technology': {'Total': 28},
 'telescope': {'diameter': {'Total': 1}},
 'thermometer': {'Total': 2},
 'thing': {'Total': 3},
 'time': {'Total': 3},
 'tmb': {'access_id': {'Total': 52},
         'code': {'Total': 1},
         'image': {'Total': 52}},
 'tobacco': {'Total': 1},
 'todo': {'Total': 1},
 'toilets': {'Total': 14,
             'disposal': {'Total': 1},
             'wheelchair': {'Total': 3}},
 'toll': {'Total': 146},
 'tou': {'Total': 1},
 'tourism': {'Total': 938},
 'tourist_bus': {'Total': 13},
 'tower': {'type': {'Total': 47}},
 'tracks': {'Total': 166},
 'tracktype': {'Total': 1296},
 'trade': {'Total': 2},
 'traffic_calming': {'Total': 98},
 'traffic_sign': {'Total': 21},
 'traffic_signals': {'direction': {'Total': 67}},
 'trail_visibility': {'Total': 271},
 'train': {'Total': 7},
 'training': {'Total': 1},
 'tram': {'Total': 208},
 'transbord': {'Total': 3},
 'transformer': {'Total': 2, 'ref': {'Total': 1}},
 'tree': {'Total': 18},
 'trees': {'Total': 2},
 'truck_scale': {'Total': 2},
 'tun': {'Total': 1},
 'tunnel': {'Total': 1342},
 'turn': {'lanes': {'forward': {'Total': 16}}},
 'type': {'Total': 297},
 'uic_ref': {'Total': 9},
 'undefined': {'Total': 1},
 'unisex': {'Total': 4},
 'url': {'Total': 34},
 'usage': {'Total': 225},
 'user_defined': {'Total': 1},
 'user_defined_other': {'Total': 1},
 'vehicle': {'Total': 20, 'backward': {'Total': 2}, 'forward': {'Total': 1}},
 'vending': {'Total': 32},
 'visibility': {'Total': 3},
 'voltage': {'Total': 1093},
 'wall': {'Total': 41},
 'waste': {'Total': 5},
 'waste_disposal': {'Total': 6},
 'water': {'Total': 94},
 'water_tank': {'volume': {'Total': 6}},
 'waterway': {'Total': 861},
 'website': {'Total': 1074, 'es': {'Total': 1}, 'reviews': {'Total': 2}},
 'weight': {'Total': 2},
 'wetap': {'credit': {'Total': 1}, 'status': {'Total': 5}},
 'wetland': {'Total': 1},
 'wheelchair': {'Total': 1263, 'description': {'Total': 16}},
 'wholesale': {'Total': 1},
 'width': {'Total': 382},
 'wifi': {'Total': 17},
 'wikidata': {'Total': 4},
 'wikipedia': {'Total': 2206,
               'en': {'Total': 16},
               'es': {'Total': 3},
               'fr': {'Total': 1},
               'hu': {'Total': 1}},
 'wires': {'Total': 1},
 'wood': {'Total': 10},
 'wpt_symbol': {'Total': 1},
 'xmas': {'day_date': {'Total': 1},
          'feature': {'Total': 1},
          'name': {'Total': 1},
          'openning_hours': {'Total': 1},
          'url': {'Total': 1}},
 'year': {'Total': 2},
 'yelp': {'Total': 1},
 'zone': {'maxspeed': {'Total': 85}},
 'zoo': {'Total': 3}}
 '''